### ISSUE TITLE
Incorrect citation

### ISSUE THREAD

**Issue by htt210** [harvardnlp/sa-vae#1]
In page 2 there is a ciation that I believe to be incorrect
"We also find that under our framework, we are
able to utilize a powerful generative model without experiencing
the “posterior-collapse” phenomenon often observed
in VAEs, wherein the variational posterior collapses to the
prior and the generative model ignores the latent variable
(Bowman et al., 2016; Chen et al., 2017; Zhao et al., 2017)."

and the Bowman et al., 2016 entry in the reference is:
Bowman, Samuel R., Vilnis, Luke, Vinyal, Oriol, Dai, Andrew M.,
Jozefowicz, Rafal, and Bengio, Samy. Categorical Reparameterization
with Gumbel-Softmax. In Proceedings of CoNLL,
2016

I cannot find the paper online. However, I can find two papers:
Bowman, Samuel R., Luke Vilnis, Oriol Vinyals, Andrew M. Dai, Rafal Jozefowicz, and Samy Bengio. "Generating sentences from a continuous space." arXiv preprint arXiv:1511.06349 (2015).

and 
Jang, Eric, Shixiang Gu, and Ben Poole. "Categorical reparameterization with gumbel-softmax." arXiv preprint arXiv:1611.01144 (2016).

**Comment by yoonkim** [comment]
thanks for identifying the error! it should be "generating sentences from a continuous space"
